### ISSUE TITLE
gnumfmt not found

### ISSUE THREAD

**Issue by hickey** [sqtran/asdf-crc#1]
On OSX, when trying to install a version of `crc` (specifically 1.29.1 in my case) the install aborts out because `gnumfmt` is not found. From what I can tell `gnumfmt` is not a standard utility installed on a OSX machine and should not be used within the `install` script.

**Comment by hickey** [comment]
Correction.... newer OSX versions (Big Sur) no longer include `gnumfmt`.

**Comment by sqtran** [comment]
Oh wow, I totally missed these notifications.  I will take a look tonight and see what's up.  Thanks for reporting the bug!

**Comment by sqtran** [comment]
And sorry for the late response, I didn't mean to leave you hanging for 20 days.

**Comment by hickey** [comment]
Not a problem. I had a similar problem a little while back where my primary email address was set to an old email and I was not getting notifications either. 

I probably will have a PR for you soon on this and #2 as running CRC on OSX came up again today. Hopefully more in a bit.
